"""
Typings for Klipper klippy.py and reactor.py
https://github.com/Klipper3d/klipper/blob/master/klippy/klippy.py
https://github.com/Klipper3d/klipper/blob/master/klippy/reactor.py
"""

from collections.abc import Callable
from typing import Any, Literal, TypeVar, overload

from klippy.extras.configfile import PrinterConfig
from klippy.extras.gcode_move import GCodeMove
from klippy.gcode import GCodeDispatch
from klippy.toolhead import ToolHead

T = TypeVar("T")

class ReactorError(Exception): ...

class ReactorTimer:
    callback: Callable[[float], float]
    waketime: float
    timer_is_running: bool

class ReactorCompletion:
    def test(self) -> bool: ...
    def complete(self, result: object) -> None: ...
    def wait(
        self, waketime: float = ..., waketime_result: object | None = None
    ) -> object: ...

class ReactorMutex:
    def test(self) -> bool: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object | None,
    ) -> None: ...

class ReactorPreventPause:
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object | None,
    ) -> None: ...

class ReactorFileHandler:
    fd: int
    read_callback: Callable[[float], object]
    write_callback: Callable[[float], object] | None

class Reactor:
    NOW: float
    NEVER: float

    def monotonic(self) -> float: ...
    def get_gc_stats(self) -> tuple[float, float, float]: ...
    def update_timer(self, timer_handler: ReactorTimer, waketime: float) -> None: ...
    def register_timer(
        self, callback: Callable[[float], float], waketime: float = ...
    ) -> ReactorTimer: ...
    def unregister_timer(self, timer_handler: ReactorTimer) -> None: ...
    def completion(self) -> ReactorCompletion: ...
    def register_callback(
        self, callback: Callable[[float], object], waketime: float = ...
    ) -> ReactorCompletion: ...
    def register_async_callback(
        self, callback: Callable[[float], object], waketime: float = ...
    ) -> None: ...
    def async_complete(self, completion: ReactorCompletion, result: object) -> None: ...
    def pause(self, waketime: float) -> float: ...
    def assert_no_pause(self) -> ReactorPreventPause: ...
    def verify_can_pause(self) -> None: ...
    def mutex(self, is_locked: bool = False) -> ReactorMutex: ...
    def register_fd(
        self,
        fd: int,
        read_callback: Callable[[float], object],
        write_callback: Callable[[float], object] | None = None,
    ) -> ReactorFileHandler: ...
    def unregister_fd(self, file_handler: ReactorFileHandler) -> None: ...
    def set_fd_wake(
        self,
        file_handler: ReactorFileHandler,
        is_readable: bool = True,
        is_writeable: bool = False,
    ) -> None: ...
    def run(self) -> None: ...
    def end(self) -> None: ...
    def finalize(self) -> None: ...

class Printer:
    config_error: type[Exception]
    command_error: type[Exception]
    start_args: dict[str, Any]

    def get_reactor(self) -> Reactor: ...
    def get_start_args(self) -> dict[str, Any]: ...
    def add_object(self, name: str, obj: object) -> None: ...
    @overload
    def lookup_object(self, name: Literal["gcode"]) -> GCodeDispatch: ...
    @overload
    def lookup_object(self, name: Literal["configfile"]) -> PrinterConfig: ...
    @overload
    def lookup_object(self, name: Literal["toolhead"]) -> ToolHead: ...
    @overload
    def lookup_object(self, name: Literal["gcode_move"]) -> GCodeMove: ...
    @overload
    def lookup_object(self, name: str, default: T) -> object | T: ...
    @overload
    def lookup_object(self, name: str) -> object: ...
    def lookup_objects(self, module: str | None = None) -> list[tuple[str, object]]: ...
    def register_event_handler(
        self, event: str, callback: Callable[..., Any]
    ) -> None: ...
    def set_rollover_info(self, name: str, info: str, log: bool = True) -> None: ...
