"""
Typings for Klipper toolhead.py
https://github.com/Klipper3d/klipper/blob/master/klippy/toolhead.py
"""

from collections.abc import Callable, Sequence
from typing import Any

from klippy.extras.configfile import ConfigWrapper

class ToolHead:
    printer: object
    reactor: object
    mcu: object
    commanded_pos: list[float]
    max_velocity: float
    max_accel: float
    min_cruise_ratio: float
    square_corner_velocity: float
    print_time: float
    print_stall: int
    can_pause: bool

    def __init__(self, config: ConfigWrapper) -> None: ...
    def _advance_move_time(self, next_print_time: float) -> None: ...
    def _calc_print_time(self) -> None: ...
    def _process_lookahead(self, lazy: bool = False) -> None: ...
    def _flush_lookahead(self, is_runout: bool = False) -> None: ...
    def _handle_step_flush(self, flush_time: float, step_gen_time: float) -> None: ...
    def flush_step_generation(self) -> None: ...
    def get_last_move_time(self) -> float: ...
    def _priming_handler(self, eventtime: float) -> float: ...
    def _check_priming_state(self, eventtime: float) -> None: ...
    def _check_pause(self) -> None: ...
    def get_position(self) -> list[float]: ...
    def set_position(self, newpos: Sequence[float], homing_axes: str = "") -> None: ...
    def limit_next_junction_speed(self, speed: float) -> None: ...
    def move(self, newpos: Sequence[float], speed: float) -> None: ...
    def manual_move(self, coord: Sequence[float | None], speed: float) -> None: ...
    def dwell(self, delay: float) -> None: ...
    def wait_moves(self) -> None: ...
    def _build_extra_axes_status(self) -> None: ...
    def set_extruder(self, extruder: object, extrude_pos: float) -> None: ...
    def get_extruder(self) -> object: ...
    def add_extra_axis(self, ea: object, axis_pos: float) -> None: ...
    def remove_extra_axis(self, ea: object) -> None: ...
    def get_extra_axes(self) -> list[object | None]: ...
    def _drip_load_trapq(self, submit_move: object) -> tuple[float, float]: ...
    def drip_move(
        self, newpos: Sequence[float], speed: float, drip_completion: object
    ) -> None: ...
    def stats(self, eventtime: float) -> tuple[bool, str]: ...
    def check_busy(self, eventtime: float) -> tuple[float, float, bool]: ...
    def get_status(self, eventtime: float) -> dict[str, Any]: ...
    def _handle_shutdown(self) -> None: ...
    def get_kinematics(self) -> object: ...
    def get_trapq(self) -> object: ...
    def register_lookahead_callback(self, callback: Callable[[float], object]) -> None:
        """Register a callback to be called when a move is completed. CB recieved move time"""
        ...

    def get_max_velocity(self) -> tuple[float, float]: ...
    def _calc_junction_deviation(self) -> None: ...
    def set_max_velocities(
        self,
        max_velocity: float | None,
        max_accel: float | None,
        square_corner_velocity: float | None,
        min_cruise_ratio: float | None,
    ) -> tuple[float, float, float, float]: ...

class ToolHeadCommandHelper:
    def __init__(self, config: ConfigWrapper) -> None: ...
    def cmd_G4(self, gcmd: object) -> None: ...
    def cmd_M400(self, gcmd: object) -> None: ...
    def cmd_SET_VELOCITY_LIMIT(self, gcmd: object) -> None: ...
    def cmd_M204(self, gcmd: object) -> None: ...
